[2023-08-31T19:12:09.027+0300] {processor.py:157} INFO - Started process (PID=18618) to work on /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-31T19:12:09.027+0300] {processor.py:829} INFO - Processing file /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-31T19:12:09.028+0300] {logging_mixin.py:151} INFO - [2023-08-31T19:12:09.028+0300] {dagbag.py:539} INFO - Filling up the DagBag from /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-31T19:12:09.030+0300] {logging_mixin.py:151} INFO - [2023-08-31T19:12:09.030+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-31T19:12:09.030+0300] {logging_mixin.py:151} INFO - [2023-08-31T19:12:09.030+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-31T19:12:09.030+0300] {processor.py:841} WARNING - No viable dags retrieved from /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-31T19:12:09.048+0300] {processor.py:179} INFO - Processing /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2023-08-31T19:12:39.954+0300] {processor.py:157} INFO - Started process (PID=18728) to work on /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-31T19:12:39.955+0300] {processor.py:829} INFO - Processing file /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-31T19:12:39.956+0300] {logging_mixin.py:151} INFO - [2023-08-31T19:12:39.955+0300] {dagbag.py:539} INFO - Filling up the DagBag from /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-31T19:12:39.958+0300] {logging_mixin.py:151} INFO - [2023-08-31T19:12:39.958+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-31T19:12:39.958+0300] {logging_mixin.py:151} INFO - [2023-08-31T19:12:39.958+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-31T19:12:39.958+0300] {processor.py:841} WARNING - No viable dags retrieved from /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-31T19:12:39.981+0300] {processor.py:179} INFO - Processing /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2023-08-31T19:13:10.067+0300] {processor.py:157} INFO - Started process (PID=18828) to work on /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-31T19:13:10.068+0300] {processor.py:829} INFO - Processing file /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-31T19:13:10.069+0300] {logging_mixin.py:151} INFO - [2023-08-31T19:13:10.068+0300] {dagbag.py:539} INFO - Filling up the DagBag from /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-31T19:13:10.071+0300] {logging_mixin.py:151} INFO - [2023-08-31T19:13:10.070+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-31T19:13:10.071+0300] {logging_mixin.py:151} INFO - [2023-08-31T19:13:10.071+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-31T19:13:10.071+0300] {processor.py:841} WARNING - No viable dags retrieved from /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-31T19:13:10.088+0300] {processor.py:179} INFO - Processing /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2023-08-31T19:13:40.204+0300] {processor.py:157} INFO - Started process (PID=18935) to work on /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-31T19:13:40.205+0300] {processor.py:829} INFO - Processing file /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-31T19:13:40.206+0300] {logging_mixin.py:151} INFO - [2023-08-31T19:13:40.206+0300] {dagbag.py:539} INFO - Filling up the DagBag from /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-31T19:13:40.209+0300] {logging_mixin.py:151} INFO - [2023-08-31T19:13:40.208+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-31T19:13:40.209+0300] {logging_mixin.py:151} INFO - [2023-08-31T19:13:40.209+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-31T19:13:40.209+0300] {processor.py:841} WARNING - No viable dags retrieved from /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-31T19:13:40.227+0300] {processor.py:179} INFO - Processing /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2023-08-31T19:14:10.275+0300] {processor.py:157} INFO - Started process (PID=19031) to work on /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-31T19:14:10.276+0300] {processor.py:829} INFO - Processing file /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-31T19:14:10.276+0300] {logging_mixin.py:151} INFO - [2023-08-31T19:14:10.276+0300] {dagbag.py:539} INFO - Filling up the DagBag from /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-31T19:14:10.279+0300] {logging_mixin.py:151} INFO - [2023-08-31T19:14:10.278+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-31T19:14:10.279+0300] {logging_mixin.py:151} INFO - [2023-08-31T19:14:10.279+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-31T19:14:10.279+0300] {processor.py:841} WARNING - No viable dags retrieved from /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-31T19:14:10.295+0300] {processor.py:179} INFO - Processing /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2023-08-31T19:14:40.364+0300] {processor.py:157} INFO - Started process (PID=19125) to work on /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-31T19:14:40.365+0300] {processor.py:829} INFO - Processing file /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-31T19:14:40.366+0300] {logging_mixin.py:151} INFO - [2023-08-31T19:14:40.365+0300] {dagbag.py:539} INFO - Filling up the DagBag from /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-31T19:14:40.368+0300] {logging_mixin.py:151} INFO - [2023-08-31T19:14:40.367+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-31T19:14:40.368+0300] {logging_mixin.py:151} INFO - [2023-08-31T19:14:40.368+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-31T19:14:40.368+0300] {processor.py:841} WARNING - No viable dags retrieved from /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-31T19:14:40.384+0300] {processor.py:179} INFO - Processing /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2023-08-31T19:15:10.730+0300] {processor.py:157} INFO - Started process (PID=19326) to work on /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-31T19:15:10.731+0300] {processor.py:829} INFO - Processing file /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-31T19:15:10.731+0300] {logging_mixin.py:151} INFO - [2023-08-31T19:15:10.731+0300] {dagbag.py:539} INFO - Filling up the DagBag from /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-31T19:15:10.734+0300] {logging_mixin.py:151} INFO - [2023-08-31T19:15:10.733+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-31T19:15:10.734+0300] {logging_mixin.py:151} INFO - [2023-08-31T19:15:10.734+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-31T19:15:10.734+0300] {processor.py:841} WARNING - No viable dags retrieved from /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-31T19:15:10.752+0300] {processor.py:179} INFO - Processing /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2023-08-31T19:15:40.936+0300] {processor.py:157} INFO - Started process (PID=19424) to work on /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-31T19:15:40.937+0300] {processor.py:829} INFO - Processing file /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-31T19:15:40.937+0300] {logging_mixin.py:151} INFO - [2023-08-31T19:15:40.937+0300] {dagbag.py:539} INFO - Filling up the DagBag from /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-31T19:15:40.940+0300] {logging_mixin.py:151} INFO - [2023-08-31T19:15:40.939+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-31T19:15:40.940+0300] {logging_mixin.py:151} INFO - [2023-08-31T19:15:40.940+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-31T19:15:40.940+0300] {processor.py:841} WARNING - No viable dags retrieved from /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-31T19:15:40.956+0300] {processor.py:179} INFO - Processing /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2023-08-31T19:16:11.348+0300] {processor.py:157} INFO - Started process (PID=19581) to work on /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-31T19:16:11.349+0300] {processor.py:829} INFO - Processing file /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-31T19:16:11.349+0300] {logging_mixin.py:151} INFO - [2023-08-31T19:16:11.349+0300] {dagbag.py:539} INFO - Filling up the DagBag from /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-31T19:16:11.355+0300] {logging_mixin.py:151} INFO - [2023-08-31T19:16:11.352+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-31T19:16:11.355+0300] {logging_mixin.py:151} INFO - [2023-08-31T19:16:11.355+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-31T19:16:11.355+0300] {processor.py:841} WARNING - No viable dags retrieved from /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-31T19:16:11.373+0300] {processor.py:179} INFO - Processing /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2023-08-31T19:16:41.675+0300] {processor.py:157} INFO - Started process (PID=19681) to work on /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-31T19:16:41.679+0300] {processor.py:829} INFO - Processing file /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-31T19:16:41.680+0300] {logging_mixin.py:151} INFO - [2023-08-31T19:16:41.679+0300] {dagbag.py:539} INFO - Filling up the DagBag from /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-31T19:16:41.682+0300] {logging_mixin.py:151} INFO - [2023-08-31T19:16:41.682+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-31T19:16:41.682+0300] {logging_mixin.py:151} INFO - [2023-08-31T19:16:41.682+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-31T19:16:41.682+0300] {processor.py:841} WARNING - No viable dags retrieved from /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-31T19:16:41.714+0300] {processor.py:179} INFO - Processing /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2023-08-31T19:17:11.880+0300] {processor.py:157} INFO - Started process (PID=19831) to work on /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-31T19:17:11.882+0300] {processor.py:829} INFO - Processing file /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-31T19:17:11.883+0300] {logging_mixin.py:151} INFO - [2023-08-31T19:17:11.883+0300] {dagbag.py:539} INFO - Filling up the DagBag from /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-31T19:17:11.885+0300] {logging_mixin.py:151} INFO - [2023-08-31T19:17:11.885+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-31T19:17:11.885+0300] {logging_mixin.py:151} INFO - [2023-08-31T19:17:11.885+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-31T19:17:11.886+0300] {processor.py:841} WARNING - No viable dags retrieved from /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-31T19:17:11.902+0300] {processor.py:179} INFO - Processing /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2023-08-31T19:17:42.138+0300] {processor.py:157} INFO - Started process (PID=19947) to work on /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-31T19:17:42.138+0300] {processor.py:829} INFO - Processing file /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-31T19:17:42.139+0300] {logging_mixin.py:151} INFO - [2023-08-31T19:17:42.138+0300] {dagbag.py:539} INFO - Filling up the DagBag from /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-31T19:17:42.141+0300] {logging_mixin.py:151} INFO - [2023-08-31T19:17:42.140+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-31T19:17:42.141+0300] {logging_mixin.py:151} INFO - [2023-08-31T19:17:42.141+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-31T19:17:42.141+0300] {processor.py:841} WARNING - No viable dags retrieved from /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-31T19:17:42.157+0300] {processor.py:179} INFO - Processing /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2023-08-31T19:18:12.241+0300] {processor.py:157} INFO - Started process (PID=20095) to work on /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-31T19:18:12.242+0300] {processor.py:829} INFO - Processing file /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-31T19:18:12.243+0300] {logging_mixin.py:151} INFO - [2023-08-31T19:18:12.242+0300] {dagbag.py:539} INFO - Filling up the DagBag from /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-31T19:18:12.245+0300] {logging_mixin.py:151} INFO - [2023-08-31T19:18:12.244+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-31T19:18:12.245+0300] {logging_mixin.py:151} INFO - [2023-08-31T19:18:12.245+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-31T19:18:12.245+0300] {processor.py:841} WARNING - No viable dags retrieved from /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-31T19:18:12.261+0300] {processor.py:179} INFO - Processing /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2023-08-31T19:18:42.400+0300] {processor.py:157} INFO - Started process (PID=20190) to work on /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-31T19:18:42.401+0300] {processor.py:829} INFO - Processing file /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-31T19:18:42.402+0300] {logging_mixin.py:151} INFO - [2023-08-31T19:18:42.401+0300] {dagbag.py:539} INFO - Filling up the DagBag from /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-31T19:18:42.404+0300] {logging_mixin.py:151} INFO - [2023-08-31T19:18:42.403+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-31T19:18:42.404+0300] {logging_mixin.py:151} INFO - [2023-08-31T19:18:42.404+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-31T19:18:42.404+0300] {processor.py:841} WARNING - No viable dags retrieved from /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-31T19:18:42.420+0300] {processor.py:179} INFO - Processing /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2023-08-31T19:19:12.891+0300] {processor.py:157} INFO - Started process (PID=20297) to work on /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-31T19:19:12.892+0300] {processor.py:829} INFO - Processing file /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-31T19:19:12.892+0300] {logging_mixin.py:151} INFO - [2023-08-31T19:19:12.892+0300] {dagbag.py:539} INFO - Filling up the DagBag from /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-31T19:19:12.894+0300] {logging_mixin.py:151} INFO - [2023-08-31T19:19:12.894+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-31T19:19:12.894+0300] {logging_mixin.py:151} INFO - [2023-08-31T19:19:12.894+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-31T19:19:12.895+0300] {processor.py:841} WARNING - No viable dags retrieved from /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-31T19:19:12.910+0300] {processor.py:179} INFO - Processing /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2023-08-31T19:19:43.324+0300] {processor.py:157} INFO - Started process (PID=20396) to work on /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-31T19:19:43.325+0300] {processor.py:829} INFO - Processing file /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-31T19:19:43.326+0300] {logging_mixin.py:151} INFO - [2023-08-31T19:19:43.325+0300] {dagbag.py:539} INFO - Filling up the DagBag from /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-31T19:19:43.328+0300] {logging_mixin.py:151} INFO - [2023-08-31T19:19:43.328+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-31T19:19:43.328+0300] {logging_mixin.py:151} INFO - [2023-08-31T19:19:43.328+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-31T19:19:43.329+0300] {processor.py:841} WARNING - No viable dags retrieved from /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-31T19:19:43.345+0300] {processor.py:179} INFO - Processing /home/miminari/repos/airflow_project/env/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
